# This is a basic workflow to help you get started with Actions

name: example-pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      site: 'https://codedor.be/nl'
    steps:
      - name: Check page title & description
        uses: Delsinvg/check-page-title-and-description-action@1.0
        id: check1
        with:
          # url of the site to check
          site: ${{env.site}}
      - name: Get the title and description
        run: echo "The title is ${{ steps.check1.outputs.title }} & the description is ${{ steps.check1.outputs.description }}"
        
      - name: Check hreflang tag
        uses: Delsinvg/check-hreflang-action@1.0
        id: check2
        with:
          # url of the site to check
          site: ${{env.site}}
      - name: Get the hreflang url
        run: echo "The website is available on ${{ steps.check2.outputs.hreflang }}"
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
